---
		title: "Pinniped Production"
output: pdf_document
date: '`r format(Sys.Date(), "%B %d, %Y")`'
---
		
		
		```{r,results="hide",echo=FALSE}
		suppressPackageStartupMessages(library(CIPinnipedAnalysis))
		source(file.path(system.file(package="CIPinnipedAnalysis"),"CuPupProduction.r"))
		maxyr=max(CuProduction$Year)
		```

# Callorhinus 

```{r,results="hide",echo=FALSE,fig.width=6,fig.height=7,dpi=300}
		par(mfrow=c(2,1))
		plot(CuProduction$Year[CuProduction$Area=="Mainland"],CuProduction$TotalLiveCountByYear[CuProduction$Area=="Mainland"],xlab="Year",ylab="Live pup count",xaxt="n",main="Mainland Northern fur seal Live Pup Count",xlim=c(1970,maxyr),ylim=c(0,2500))
		lines(CuProduction$Year[CuProduction$Area=="Mainland"],CuProduction$TotalLiveCountByYear[CuProduction$Area=="Mainland"])
		axis(1,at=seq(1970,maxyr,2),labels= seq(1970,maxyr,2))
		cr.years=CuProduction$Year[CuProduction$Area=="CastleRock"]
		cr.prod=CuProduction$PupProduction[CuProduction$Area=="CastleRock"]
		years=1970:max(cr.years)
		missing.years=years[!years%in%cr.years]
		cr.prod=c(cr.prod,rep(NA,length(missing.years)))
		cr.years=c(cr.years,missing.years)
		cr.prod=cr.prod[order(cr.years)]
		cr.years=sort(cr.years)
		plot(cr.years,cr.prod,main="Castle Rock Northern fur seal Live Pup Count",xlab="Year",ylab="Pup production",xaxt="n",xlim=c(1970,maxyr), ylim=c(0,1500))
		lines(cr.years,cr.prod)
		axis(1,at=seq(1970,maxyr,2),labels= seq(1970,maxyr,2))
		```

Figure 4. Count of live Callorhinus pups on San Miguel Island

```{r,results="hide",echo=FALSE,fig.width=6,fig.height=7,dpi=300}
		plot(CuProduction$Year[CuProduction$Area=="Mainland"],CuProduction$MortalityRateAtLiveCount[CuProduction$Area=="Mainland"],xlab="Year",ylab="Mortality",xaxt="n",main="Cu Mainland Pre-census Mortality",xlim=c(1970,maxyr))
		lines(CuProduction$Year[CuProduction$Area=="Mainland"],CuProduction$MortalityRateAtLiveCount[CuProduction$Area=="Mainland"])
		axis(1,at=seq(1970,maxyr,2),labels= seq(1970,maxyr,2))
		```

Figure 5. Pre-census Callorhinus pup mortality rate


```{r,results="hide",echo=FALSE,fig.width=6,fig.height=7,dpi=300}
		par(mfrow=c(2,1))
		plot(CuProduction$Year[CuProduction$Area=="Mainland"],CuProduction$PupProduction[CuProduction$Area=="Mainland"],xlab="Year",ylab="Pup production",xaxt="n",main="Northern fur seals Mainland")
		lines(CuProduction$Year[CuProduction$Area=="Mainland"],CuProduction$PupProduction[CuProduction$Area=="Mainland"])
		axis(1,at=seq(1970,maxyr,2),labels= seq(1970,maxyr,2))
		
		cr.years=CuProduction$Year[CuProduction$Area=="CastleRock"]
		cr.prod=CuProduction$PupProduction[CuProduction$Area=="CastleRock"]
		years=1970:max(cr.years)
		missing.years=years[!years%in%cr.years]
		cr.prod=c(cr.prod,rep(NA,length(missing.years)))
		cr.years=c(cr.years,missing.years)
		cr.prod=cr.prod[order(cr.years)]
		cr.years=sort(cr.years)
		plot(cr.years,cr.prod,main="Northern fur seals Castle Rock",xlab="Year",ylab="Pup production",xaxt="n",xlim=c(1970,maxyr))
		lines(cr.years,cr.prod)
		axis(1,at=seq(1970,maxyr,2),labels= seq(1970,maxyr,2))
		```

Figure 6. Estimated pup production of Callorhinus pups on San Miguel Island






