if(use.calcofi)
{
	fixed.f=list(		
			weight~sex*SST+sex:days+SST1:days+sex:SST1:days+cohort,
			weight~sex*SST+sex:days+SST1:days+sex:SST1:days,
			weight~sex*SST+sex:days+SST1:days+cohort,
			weight~sex*SST+sex:days+SST1:days,
			weight~sex*SST+sex:days+cohort,
			weight~sex*SST+sex:days,
			weight~sex+SST+sex:days+SST1:days+sex:SST1:days+cohort,
			weight~sex+SST+sex:days+SST1:days+sex:SST1:days,
			weight~sex+SST+sex:days+SST1:days+cohort,
			weight~sex+SST+sex:days+SST1:days,
			weight~sex+SST+sex:days+cohort,
			weight~sex+SST+sex:days,
			
			weight~sex*SLH+sex:days+SLH1:days+sex:SLH1:days+cohort,
			weight~sex*SLH+sex:days+SLH1:days+sex:SLH1:days,
			weight~sex*SLH+sex:days+SLH1:days+cohort,
			weight~sex*SLH+sex:days+SLH1:days,
			weight~sex*SLH+sex:days+cohort,
			weight~sex*SLH+sex:days,
			weight~sex+SLH+sex:days+SLH1:days+sex:SLH1:days+cohort,
			weight~sex+SLH+sex:days+SLH1:days+sex:SLH1:days,
			weight~sex+SLH+sex:days+SLH1:days+cohort,
			weight~sex+SLH+sex:days+SLH1:days,
			weight~sex+SLH+sex:days+cohort,
			weight~sex+SLH+sex:days,
			
			weight~sex*MEI+sex:days+MEI1:days+sex:MEI1:days+cohort,
			weight~sex*MEI+sex:days+MEI1:days+sex:MEI1:days,
			weight~sex*MEI+sex:days+MEI1:days+cohort,
			weight~sex*MEI+sex:days+MEI1:days,
			weight~sex*MEI+sex:days+cohort,
			weight~sex*MEI+sex:days,
			weight~sex+MEI+sex:days+MEI1:days+sex:MEI1:days+cohort,
			weight~sex+MEI+sex:days+MEI1:days+sex:MEI1:days,
			weight~sex+MEI+sex:days+MEI1:days+cohort,
			weight~sex+MEI+sex:days+MEI1:days,
			weight~sex+MEI+sex:days+cohort,
			weight~sex+MEI+sex:days,
			
			weight~sex*UWI36+sex:days+UWI361:days+sex:UWI361:days+cohort,
			weight~sex*UWI36+sex:days+UWI361:days+sex:UWI361:days,
			weight~sex*UWI36+sex:days+UWI361:days+cohort,
			weight~sex*UWI36+sex:days+UWI361:days,
			weight~sex*UWI36+sex:days+cohort,
			weight~sex*UWI36+sex:days,
			weight~sex+UWI36+sex:days+UWI361:days+sex:UWI361:days+cohort,
			weight~sex+UWI36+sex:days+UWI361:days+sex:UWI361:days,
			weight~sex+UWI36+sex:days+UWI361:days+cohort,
			weight~sex+UWI36+sex:days+UWI361:days,
			weight~sex+UWI36+sex:days+cohort,
			weight~sex+UWI36+sex:days,
			
			weight~sex*dynamic_height_0_500m+sex:days+dynamic_height_0_500m.oct:days+sex:dynamic_height_0_500m.oct:days+cohort,
			weight~sex*dynamic_height_0_500m+sex:days+dynamic_height_0_500m.oct:days+sex:dynamic_height_0_500m.oct:days,
			weight~sex*dynamic_height_0_500m+sex:days+dynamic_height_0_500m.oct:days+cohort,
			weight~sex*dynamic_height_0_500m+sex:days+dynamic_height_0_500m.oct:days,
			weight~sex*dynamic_height_0_500m+sex:days+cohort,
			weight~sex*dynamic_height_0_500m+sex:days,
			weight~sex+dynamic_height_0_500m+sex:days+dynamic_height_0_500m.oct:days+sex:dynamic_height_0_500m.oct:days+cohort,
			weight~sex+dynamic_height_0_500m+sex:days+dynamic_height_0_500m.oct:days+sex:dynamic_height_0_500m.oct:days,
			weight~sex+dynamic_height_0_500m+sex:days+dynamic_height_0_500m.oct:days+cohort,
			weight~sex+dynamic_height_0_500m+sex:days+dynamic_height_0_500m.oct:days,
			weight~sex+dynamic_height_0_500m+sex:days+cohort,
			weight~sex+dynamic_height_0_500m+sex:days,
			
			weight~sex*poly(dynamic_height_0_500m,2)+sex:days+poly(dynamic_height_0_500m.oct,2):days+sex:poly(dynamic_height_0_500m.oct,2):days+cohort,
			weight~sex*poly(dynamic_height_0_500m,2)+sex:days+poly(dynamic_height_0_500m.oct,2):days+sex:poly(dynamic_height_0_500m.oct,2):days,
			weight~sex*poly(dynamic_height_0_500m,2)+sex:days+poly(dynamic_height_0_500m.oct,2):days+cohort,
			weight~sex*poly(dynamic_height_0_500m,2)+sex:days+poly(dynamic_height_0_500m.oct,2):days,
			weight~sex*poly(dynamic_height_0_500m,2)+sex:days+cohort,
			weight~sex*poly(dynamic_height_0_500m,2)+sex:days,
			weight~sex+poly(dynamic_height_0_500m,2)+sex:days+poly(dynamic_height_0_500m.oct,2):days+sex:poly(dynamic_height_0_500m.oct,2):days+cohort,
			weight~sex+poly(dynamic_height_0_500m,2)+sex:days+poly(dynamic_height_0_500m.oct,2):days+sex:poly(dynamic_height_0_500m.oct,2):days,
			weight~sex+poly(dynamic_height_0_500m,2)+sex:days+poly(dynamic_height_0_500m.oct,2):days+cohort,
			weight~sex+poly(dynamic_height_0_500m,2)+sex:days+poly(dynamic_height_0_500m.oct,2):days,
			weight~sex+poly(dynamic_height_0_500m,2)+sex:days+cohort,
			weight~sex+poly(dynamic_height_0_500m,2)+sex:days,
			#			weight~sex*R_SIGMA_75m+sex:days+R_SIGMA_75m.oct:days+sex:R_SIGMA_75m.oct:days+cohort,
#			weight~sex*R_SIGMA_75m+sex:days+R_SIGMA_75m.oct:days+sex:R_SIGMA_75m.oct:days,
#			weight~sex*R_SIGMA_75m+sex:days+R_SIGMA_75m.oct:days+cohort,
#			weight~sex*R_SIGMA_75m+sex:days+R_SIGMA_75m.oct:days,
#			weight~sex*R_SIGMA_75m+sex:days+cohort,
#			weight~sex*R_SIGMA_75m+sex:days,
#			weight~sex+R_SIGMA_75m+sex:days+R_SIGMA_75m.oct:days+sex:R_SIGMA_75m.oct:days+cohort,
#			weight~sex+R_SIGMA_75m+sex:days+R_SIGMA_75m.oct:days+sex:R_SIGMA_75m.oct:days,
#			weight~sex+R_SIGMA_75m+sex:days+R_SIGMA_75m.oct:days+cohort,
#			weight~sex+R_SIGMA_75m+sex:days+R_SIGMA_75m.oct:days,
#			weight~sex+R_SIGMA_75m+sex:days+cohort,
#			weight~sex+R_SIGMA_75m+sex:days,
			
			weight~sex*R_POTEMP_75m+sex:days+R_POTEMP_75m.oct:days+sex:R_POTEMP_75m.oct:days+cohort,
			weight~sex*R_POTEMP_75m+sex:days+R_POTEMP_75m.oct:days+sex:R_POTEMP_75m.oct:days,
			weight~sex*R_POTEMP_75m+sex:days+R_POTEMP_75m.oct:days+cohort,
			weight~sex*R_POTEMP_75m+sex:days+R_POTEMP_75m.oct:days,
			weight~sex*R_POTEMP_75m+sex:days+cohort,
			weight~sex*R_POTEMP_75m+sex:days,
			weight~sex+R_POTEMP_75m+sex:days+R_POTEMP_75m.oct:days+sex:R_POTEMP_75m.oct:days+cohort,
			weight~sex+R_POTEMP_75m+sex:days+R_POTEMP_75m.oct:days+sex:R_POTEMP_75m.oct:days,
			weight~sex+R_POTEMP_75m+sex:days+R_POTEMP_75m.oct:days+cohort,
			weight~sex+R_POTEMP_75m+sex:days+R_POTEMP_75m.oct:days,
			weight~sex+R_POTEMP_75m+sex:days+cohort,
			weight~sex+R_POTEMP_75m+sex:days,
			
			weight~sex*stratification+sex:days+stratification.oct:days+sex:stratification.oct:days+cohort,
			weight~sex*stratification+sex:days+stratification.oct:days+sex:stratification.oct:days,
			weight~sex*stratification+sex:days+stratification.oct:days+cohort,
			weight~sex*stratification+sex:days+stratification.oct:days,
			weight~sex*stratification+sex:days+cohort,
			weight~sex*stratification+sex:days,
			weight~sex+stratification+sex:days+stratification.oct:days+sex:stratification.oct:days+cohort,
			weight~sex+stratification+sex:days+stratification.oct:days+sex:stratification.oct:days,
			weight~sex+stratification+sex:days+stratification.oct:days+cohort,
			weight~sex+stratification+sex:days+stratification.oct:days,
			weight~sex+stratification+sex:days+cohort,
			weight~sex+stratification+sex:days,
			
			weight~sex*pycnocline_depth+sex:days+pycnocline_depth.oct:days+sex:pycnocline_depth.oct:days+cohort,
			weight~sex*pycnocline_depth+sex:days+pycnocline_depth.oct:days+sex:pycnocline_depth.oct:days,
			weight~sex*pycnocline_depth+sex:days+pycnocline_depth.oct:days+cohort,
			weight~sex*pycnocline_depth+sex:days+pycnocline_depth.oct:days,
			weight~sex*pycnocline_depth+sex:days+cohort,
			weight~sex*pycnocline_depth+sex:days,
			weight~sex+pycnocline_depth+sex:days+pycnocline_depth.oct:days+sex:pycnocline_depth.oct:days+cohort,
			weight~sex+pycnocline_depth+sex:days+pycnocline_depth.oct:days+sex:pycnocline_depth.oct:days,
			weight~sex+pycnocline_depth+sex:days+pycnocline_depth.oct:days+cohort,
			weight~sex+pycnocline_depth+sex:days+pycnocline_depth.oct:days,
			weight~sex+pycnocline_depth+sex:days+cohort,
			weight~sex+pycnocline_depth+sex:days,
			
			weight~sex*R_O2_75m+sex:days+R_O2_75m.oct:days+sex:R_O2_75m.oct:days+cohort,
			weight~sex*R_O2_75m+sex:days+R_O2_75m.oct:days+sex:R_O2_75m.oct:days,
			weight~sex*R_O2_75m+sex:days+R_O2_75m.oct:days+cohort,
			weight~sex*R_O2_75m+sex:days+R_O2_75m.oct:days,
			weight~sex*R_O2_75m+sex:days+cohort,
			weight~sex*R_O2_75m+sex:days,
			weight~sex+R_O2_75m+sex:days+R_O2_75m.oct:days+sex:R_O2_75m.oct:days+cohort,
			weight~sex+R_O2_75m+sex:days+R_O2_75m.oct:days+sex:R_O2_75m.oct:days,
			weight~sex+R_O2_75m+sex:days+R_O2_75m.oct:days+cohort,
			weight~sex+R_O2_75m+sex:days+R_O2_75m.oct:days,
			weight~sex+R_O2_75m+sex:days+cohort,
			weight~sex+R_O2_75m+sex:days,
			
			weight~sex*R_NO3_75m+sex:days+R_NO3_75m.oct:days+sex:R_NO3_75m.oct:days+cohort,
			weight~sex*R_NO3_75m+sex:days+R_NO3_75m.oct:days+sex:R_NO3_75m.oct:days,
			weight~sex*R_NO3_75m+sex:days+R_NO3_75m.oct:days+cohort,
			weight~sex*R_NO3_75m+sex:days+R_NO3_75m.oct:days,
			weight~sex*R_NO3_75m+sex:days+cohort,
			weight~sex*R_NO3_75m+sex:days,
			weight~sex+R_NO3_75m+sex:days+R_NO3_75m.oct:days+sex:R_NO3_75m.oct:days+cohort,
			weight~sex+R_NO3_75m+sex:days+R_NO3_75m.oct:days+sex:R_NO3_75m.oct:days,
			weight~sex+R_NO3_75m+sex:days+R_NO3_75m.oct:days+cohort,
			weight~sex+R_NO3_75m+sex:days+R_NO3_75m.oct:days,
			weight~sex+R_NO3_75m+sex:days+cohort,
			weight~sex+R_NO3_75m+sex:days)
} else
{
	fixed.f=list(
			weight~sex*SST+sex:days+SST1:days+sex:SST1:days+cohort,
			weight~sex*SST+sex:days+SST1:days+sex:SST1:days,
			weight~sex*SST+sex:days+SST1:days+cohort,
			weight~sex*SST+sex:days+SST1:days,
			weight~sex*SST+sex:days+cohort,
			weight~sex*SST+sex:days,
			weight~sex+SST+sex:days+SST1:days+sex:SST1:days+cohort,
			weight~sex+SST+sex:days+SST1:days+sex:SST1:days,
			weight~sex+SST+sex:days+SST1:days+cohort,
			weight~sex+SST+sex:days+SST1:days,
			weight~sex+SST+sex:days+cohort,
			weight~sex+SST+sex:days,
#			weight~sex*SST+sex:days+SST1:days+sex:SST1:days+density,
#			weight~sex*SST+sex:days+SST1:days+sex:SST1:days+density+density:SST,
#			weight~sex*SST+sex:days+SST1:days+density,
#			weight~sex*SST+sex:days+SST1:days+density+density:SST,
#			weight~sex*SST+sex:days+density+density:SST,
#			weight~sex*SST+sex:days+density,
#			weight~sex+SST+sex:days+SST1:days+sex:SST1:days+density,
#			weight~sex+SST+sex:days+SST1:days+sex:SST1:days+density+density:SST,
#			weight~sex+SST+sex:days+SST1:days+density,
#			weight~sex+SST+sex:days+SST1:days+density+density:SST,
#			weight~sex+SST+sex:days+density+density:SST,
#			weight~sex+SST+sex:days+density,
			
			weight~sex*SLH+sex:days+SLH1:days+sex:SLH1:days+cohort,
			weight~sex*SLH+sex:days+SLH1:days+sex:SLH1:days,
			weight~sex*SLH+sex:days+SLH1:days+cohort,
			weight~sex*SLH+sex:days+SLH1:days,
			weight~sex*SLH+sex:days+cohort,
			weight~sex*SLH+sex:days,
			weight~sex+SLH+sex:days+SLH1:days+sex:SLH1:days+cohort,
			weight~sex+SLH+sex:days+SLH1:days+sex:SLH1:days,
			weight~sex+SLH+sex:days+SLH1:days+cohort,
			weight~sex+SLH+sex:days+SLH1:days,
			weight~sex+SLH+sex:days+cohort,
			weight~sex+SLH+sex:days,
#			weight~sex*SLH+sex:days+SLH1:days+sex:SLH1:days+density,
#			weight~sex*SLH+sex:days+SLH1:days+sex:SLH1:days+density+density:SLH,
#			weight~sex*SLH+sex:days+SLH1:days+density,
#			weight~sex*SLH+sex:days+SLH1:days+density+density:SLH,
#			weight~sex*SLH+sex:days+density+density:SLH,
#			weight~sex*SLH+sex:days+density,
#			weight~sex+SLH+sex:days+SLH1:days+sex:SLH1:days+density,
#			weight~sex+SLH+sex:days+SLH1:days+sex:SLH1:days+density+density:SLH,
#			weight~sex+SLH+sex:days+SLH1:days+density,
#			weight~sex+SLH+sex:days+SLH1:days+density+density:SLH,
#			weight~sex+SLH+sex:days+density+density:SLH,
#			weight~sex+SLH+sex:days+density,
			
			weight~sex*MEI+sex:days+MEI1:days+sex:MEI1:days+cohort,
			weight~sex*MEI+sex:days+MEI1:days+sex:MEI1:days,
			weight~sex*MEI+sex:days+MEI1:days+cohort,
			weight~sex*MEI+sex:days+MEI1:days,
			weight~sex*MEI+sex:days+cohort,
			weight~sex*MEI+sex:days,
			weight~sex+MEI+sex:days+MEI1:days+sex:MEI1:days+cohort,
			weight~sex+MEI+sex:days+MEI1:days+sex:MEI1:days,
			weight~sex+MEI+sex:days+MEI1:days+cohort,
			weight~sex+MEI+sex:days+MEI1:days,
			weight~sex+MEI+sex:days+cohort,
			weight~sex+MEI+sex:days,
#			weight~sex*MEI+sex:days+MEI1:days+sex:MEI1:days+density,
#			weight~sex*MEI+sex:days+MEI1:days+sex:MEI1:days+density+density:MEI,
#			weight~sex*MEI+sex:days+MEI1:days+density,
#			weight~sex*MEI+sex:days+MEI1:days+density+density:MEI,
#			weight~sex*MEI+sex:days+density,
#			weight~sex*MEI+sex:days+density+density:MEI,
#			weight~sex+MEI+sex:days+MEI1:days+sex:MEI1:days+density,
#			weight~sex+MEI+sex:days+MEI1:days+sex:MEI1:days+density+density:MEI,
#			weight~sex+MEI+sex:days+MEI1:days+density,
#			weight~sex+MEI+sex:days+MEI1:days+density+density:MEI,
#			weight~sex+MEI+sex:days+density,
#			weight~sex+MEI+sex:days+density+density:MEI,
			
			weight~sex*PDO+sex:days+PDO1:days+sex:PDO1:days+cohort,
			weight~sex*PDO+sex:days+PDO1:days+sex:PDO1:days,
			weight~sex*PDO+sex:days+PDO1:days+cohort,
			weight~sex*PDO+sex:days+PDO1:days,
			weight~sex*PDO+sex:days+cohort,
			weight~sex*PDO+sex:days,
			weight~sex+PDO+sex:days+PDO1:days+sex:PDO1:days+cohort,
			weight~sex+PDO+sex:days+PDO1:days+sex:PDO1:days,
			weight~sex+PDO+sex:days+PDO1:days+cohort,
			weight~sex+PDO+sex:days+PDO1:days,
			weight~sex+PDO+sex:days+cohort,
			weight~sex+PDO+sex:days,
#			weight~sex*PDO+sex:days+PDO1:days+sex:PDO1:days+density,
#			weight~sex*PDO+sex:days+PDO1:days+sex:PDO1:days+density+density:PDO,
#			weight~sex*PDO+sex:days+PDO1:days+density,
#			weight~sex*PDO+sex:days+PDO1:days+density+density:PDO,
#			weight~sex*PDO+sex:days+density,
#			weight~sex*PDO+sex:days+density+density:PDO,
#			weight~sex+PDO+sex:days+PDO1:days+sex:PDO1:days+density,
#			weight~sex+PDO+sex:days+PDO1:days+sex:PDO1:days+density+density:PDO,
#			weight~sex+PDO+sex:days+PDO1:days+density,
#			weight~sex+PDO+sex:days+density,
#			weight~sex+PDO+sex:days+density+density:PDO,
			
			weight~sex*NPGO+sex:days+NPGO1:days+sex:NPGO1:days+cohort,
			weight~sex*NPGO+sex:days+NPGO1:days+sex:NPGO1:days,
			weight~sex*NPGO+sex:days+NPGO1:days+cohort,
			weight~sex*NPGO+sex:days+NPGO1:days,
			weight~sex*NPGO+sex:days+cohort,
			weight~sex*NPGO+sex:days,
			weight~sex+NPGO+sex:days+NPGO1:days+sex:NPGO1:days+cohort,
			weight~sex+NPGO+sex:days+NPGO1:days+sex:NPGO1:days,
			weight~sex+NPGO+sex:days+NPGO1:days+cohort,
			weight~sex+NPGO+sex:days+NPGO1:days,
			weight~sex+NPGO+sex:days+cohort,
			weight~sex+NPGO+sex:days,
#			weight~sex*NPGO+sex:days+NPGO1:days+sex:NPGO1:days+density,
#			weight~sex*NPGO+sex:days+NPGO1:days+sex:NPGO1:days+density+density:NPGO,
#			weight~sex*NPGO+sex:days+NPGO1:days+density,
#			weight~sex*NPGO+sex:days+NPGO1:days+density+density:NPGO,
#			weight~sex*NPGO+sex:days+density,
#			weight~sex*NPGO+sex:days+density+density:NPGO,
#			weight~sex+NPGO+sex:days+NPGO1:days+sex:NPGO1:days+density+density:NPGO,
#			weight~sex+NPGO+sex:days+NPGO1:days+density,
#			weight~sex+NPGO+sex:days+NPGO1:days+density+density:NPGO,
#			weight~sex+NPGO+sex:days+density,
#			weight~sex+NPGO+sex:days+density+density:NPGO,
			
			weight~sex*UWI36+sex:days+UWI361:days+sex:UWI361:days+cohort,
			weight~sex*UWI36+sex:days+UWI361:days+sex:UWI361:days,
			weight~sex*UWI36+sex:days+UWI361:days+cohort,
			weight~sex*UWI36+sex:days+UWI361:days,
			weight~sex*UWI36+sex:days+cohort,
			weight~sex*UWI36+sex:days,
			weight~sex+UWI36+sex:days+UWI361:days+sex:UWI361:days+cohort,
			weight~sex+UWI36+sex:days+UWI361:days+sex:UWI361:days,
			weight~sex+UWI36+sex:days+UWI361:days+cohort,
			weight~sex+UWI36+sex:days+UWI361:days,
			weight~sex+UWI36+sex:days+cohort,
			weight~sex+UWI36+sex:days
#			weight~sex*UWI36+sex:days+UWI361:days+sex:UWI361:days+density,
#			weight~sex*UWI36+sex:days+UWI361:days+sex:UWI361:days+density+density:UWI36,
#			weight~sex*UWI36+sex:days+UWI361:days+density,
#			weight~sex*UWI36+sex:days+UWI361:days+density+density:UWI36,
#			weight~sex*UWI36+sex:days+density,
#			weight~sex*UWI36+sex:days+density+density:UWI36,
#			weight~sex+UWI36+sex:days+UWI361:days+sex:UWI361:days+density+density:UWI36,
#			weight~sex+UWI36+sex:days+UWI361:days+density,
#			weight~sex+UWI36+sex:days+UWI361:days+density+density:UWI36,
#			weight~sex+UWI36+sex:days+density,
#			weight~sex+UWI36+sex:days+density+density:UWI36)
)
}
